---
type: object
properties:
  logging:
    type: object
    properties:
      modlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      reactlog:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
  staff:
    type: object
    properties:
      adminrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      modrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      botrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      staffchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      rulesurl:
        type:
          - string
          - "null"
      appealurl:
        type:
          - string
          - "null"
  toss:
    type: object
    properties:
      tossrole:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      tosscategory:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      notificationchannel:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      tosschannels:
        type: 
          - array
          - "null"
        items:
          type:
            - integer
            - string
          minimum: 100000000000000000
      tosstopic:
        type: 
          - string
          - "null"
      tossmsg:
        type:
          - string
          - "null"
      tossmsg_rejoin:
        type:
          - string
          - "null"
      tossmsg_noreply:
        type:
          - string
          - "null"
      tossmsg_noreply_blocked:
        type:
          - string
          - "null"

  reaction:
    type: object
    properties:
      autoreadableenable:
        type:
          - boolean
          - "null"
      noreply_threshold:
        type:
          - integer
          - "null"
      noreply_remind_every:
        type:
          - integer
          - "null"
      please_ping_emoji:
        type:
          - string
          - "null"
      no_ping_emoji:
        type:
          - string
          - "null"
      wait_ping_emoji:
        type:
          - string
          - "null"
      whitelist_ping_emoji:
        type:
          - string
          - "null"
  tenure:
    type: object
    properties:
      threshold:
        type:
          - integer
          - "null"
      role:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
      role_disabled:
        type:
          - integer
          - string
          - "null"
        minimum: 100000000000000000
  starboard:
    type: object
    properties:
      queue_channel:
        type:
          - integer
          - string
          - "null"
      starboard_channel:
        type:
          - integer
          - string
          - "null"
  overrides:
    type:
      - array
      - "null"
    items:
      type: object
      properties:
        command:
          type: string
        roles:
          type: array
          items:
            type:
              - integer
              - string
            minimum: 100000000000000000
        restrict:
          type: boolean
  drive:
    type: object
    properties:
      folder:
        type: 
          - string
          - "null"
  metadata:
    type: object
    properties:
      version:
        const: 22
